version: '2'

services:
  jupyter:
    container_name: ${JUPYTER_CONTAINER_NAME}
    hostname: ${JUPYTER_CONTAINER_NAME}
    image: dibimbing-final/jupyter
    ports:
      - ${JUPYTER_PORT}:8888
      - 4040:4040
      - 4041:4041
    volumes:
      - ../notebooks:/home/jovyan/
      - ../.env:/opt/app/.env

networks:
  default:
    name: dibimbing-network
    external: true
