version: '3'

services:
  metabase:
    image: metabase/metabase:v0.47.3
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabaseappdb
      - MB_DB_HOST=host.docker.internal
      - MB_DB_USER=${POSTGRES_USER}
      - MB_DB_PASS=${POSTGRES_PASSWORD}
      - MB_DB_PORT=${POSTGRES_PORT}
    restart: always

networks:
  default:
    name: dibimbing-network
    external: true
